import { app, shell } from 'electron'
import { readdir, stat, access } from 'node:fs/promises'
import { constants } from 'node:fs'
import path from 'node:path'

/**
 * Auto-update, and cleaning up after it.
 *
 * M1 exists because Squirrel.Mac and electron-updater download a full
 * application archive for every update and never delete it — 1.9 GB of spent
 * installers on the reference machine, from four apps. This app uses the same
 * machinery, so it would accumulate the same rubbish.
 *
 * It does not, because it removes its own leftovers on launch. Shipping a
 * storage cleaner that leaks storage would be indefensible.
 *
 * `electron-updater` is loaded lazily and only in a packaged build: it has no
 * meaning in development, and importing it unconditionally would make `npm run
 * dev` depend on a module the dev flow never uses.
 */

/** Where electron-updater stages downloads: userData/../<name>-updater. */
function updaterCacheDir(): string {
  return path.join(app.getPath('userData'), '..', `${app.getName()}-updater`)
}

const DAY_MS = 24 * 60 * 60 * 1000

/**
 * Removes update archives left over from versions already installed.
 *
 * Anything still being written is left alone (the one-day floor), and the
 * removal goes to the Trash like everything else this app deletes — the rule
 * about never calling `fs.rm` has no exception for our own files.
 */
export async function cleanUpdaterResidue(): Promise<number> {
  const dir = updaterCacheDir()
  let removed = 0

  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return 0 // never updated, or nothing staged
  }

  for (const entry of entries) {
    // `pending` is the staging directory; the rest are completed downloads.
    if (!/\.(zip|dmg)$/i.test(entry.name) && entry.name !== 'pending') continue

    const full = path.join(dir, entry.name)

    try {
      const info = await stat(full)
      if (Date.now() - info.mtimeMs < DAY_MS) continue

      await shell.trashItem(full)
      removed += 1
    } catch {
      continue
    }
  }

  return removed
}

export interface UpdaterOptions {
  /** Called when an update has been downloaded and is ready to install. */
  onReady: (version: string) => void
}

export async function initAutoUpdate(options: UpdaterOptions): Promise<void> {
  // Nothing to update in development, and an unsigned build cannot verify a
  // signature anyway.
  if (!app.isPackaged) return

  const removed = await cleanUpdaterResidue()
  if (removed > 0) {
    console.log(`[updater] moved ${removed} spent update archive(s) to the Trash`)
  }

  // Generated by electron-builder only for real distribution targets. Its
  // absence means this build was never meant to update itself (a `--dir` build,
  // or a copy someone assembled by hand), which is not an error worth logging.
  try {
    await access(path.join(process.resourcesPath, 'app-update.yml'), constants.R_OK)
  } catch {
    return
  }

  try {
    // electron-updater is CommonJS, so a dynamic import from ESM wraps it in
    // `default`. Destructuring `autoUpdater` directly yields undefined and the
    // updater fails silently — which it did, in the first packaged build.
    const updaterModule = await import('electron-updater')
    const autoUpdater = updaterModule.default?.autoUpdater ?? updaterModule.autoUpdater

    if (!autoUpdater) throw new Error('electron-updater exported no autoUpdater')

    autoUpdater.autoDownload = true
    // Installing behind the user's back is how an app loses unsaved work.
    autoUpdater.autoInstallOnAppQuit = true

    autoUpdater.on('update-downloaded', (info: { version: string }) => {
      options.onReady(info.version)
      // Clear the previous archive as soon as a newer one supersedes it.
      void cleanUpdaterResidue()
    })

    autoUpdater.on('error', (error: Error) => {
      // A failed update check must never interrupt the app.
      console.error(`[updater] ${error.message}`)
    })

    await autoUpdater.checkForUpdates()
  } catch (error) {
    console.error(
      `[updater] disabled: ${error instanceof Error ? error.message : String(error)}`
    )
  }
}
